- hosts: localhost
  tasks:
  - yum_repository:
      name: "docker"
      description: "My Docker"
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      gpgcheck: no
  - package:
      name:
      - "docker-ce-18.09.1-3.el7.x86_64"
      state: present
  - service:
      name: "docker"
      state: started
      enabled: yes
  - command: pip3 install docker
  - file:
      path: /var/www/html/docker2.html
      state: directory
  - copy:
      dest: "/var/www/html/docker2.html"
      src: "/ansiblews/doc.html"
  - docker_image:
      name: httpd
      source: pull
  - docker_container:
      name: dynamic_inventory
      image: httpd
      volumes:
      - /var/www/html/docker2.html:/usr/local/apache2/htdocs/
      state: started
      exposed_ports:
      - "80"
      ports:
      - "8888:80"
    register: docker_info
  - debug:
       var: docker_info.ansible_facts.docker_container.NetworkSettings.IPAddress
  - name: retreiving ip and adding to inventory
    template:
       src: /ansiblews/dynamicip.txt
       dest: /root/ip.txt
